"""Deterministic markdown renderer.

Takes plan.json + profile JSON, emits a fully formatted markdown that
PASSES validate_output.py — no LLM free-form writing involved, so there
is no opportunity to hallucinate catalog-absent jobs or unsourced wages.
"""
from __future__ import annotations

import json
from typing import Dict, List

from .catalog import TYPE_EMOJI, TYPE_KEYS, load_catalog
from .rationale import build_rationale_sentence, derive_profile_keys


TYPE_HEADER_KO = {
    "future": "Type 1 — Future Jobs (미래 직업)",
    "happy_fun": "Type 2 — Happy & Fun Jobs (행복·재미)",
    "retirement": "Type 3 — Retirement Volunteering (은퇴 후 사회·종교 자원봉사)",
    "high_pay": "Type 4 — High-Pay Current (현재 고소득 직업)",
}
TYPE_HEADER_EN = {
    "future": "Type 1 — Future Jobs",
    "happy_fun": "Type 2 — Happy & Fun Jobs",
    "retirement": "Type 3 — Retirement Volunteering",
    "high_pay": "Type 4 — High-Pay Current",
}

VERDICT_LABEL_KO = {
    "pass": "✓ 적합",
    "borderline": "△ 약간 미달 — 보완 경로 필요",
    "unknown": "? 나이·학력 미확인",
    "unfilled": "⚠ 적합 직업 부족 (자료 기반 placeholder)",
}
VERDICT_LABEL_EN = {
    "pass": "Fit",
    "borderline": "Borderline — supplementation needed",
    "unknown": "Unknown — age/education undisclosed",
    "unfilled": "Catalog gap — placeholder",
}


def _work_type_advice(type_key: str, lang: str) -> str:
    if lang == "en":
        return {
            "future": "Large-cap/midsize/public-org full-time roles; hybrid/remote-friendly variants exist.",
            "happy_fun": "Often start as side projects or 1-person business; scale into full-time if traction.",
            "retirement": "Volunteer/part-time/advisory — see explore-mode if user is under 55.",
            "high_pay": "Full-time, in-office or hybrid; work-life balance varies sharply by industry.",
        }[type_key]
    return {
        "future": "대기업·중견·공공기관 정규직 또는 하이브리드/원격 친화 직무.",
        "happy_fun": "사이드/부업으로 시작 → 정규/1인 사업 확장. 풀타임 전환은 안정 후.",
        "retirement": "자원봉사·자문·파트타임 중심. 55세 미만 사용자는 *예비 탐색* 관점.",
        "high_pay": "정규직 풀타임 중심. 워라밸 강도는 산업·기업별 큰 편차 존재.",
    }[type_key]


def render_markdown(plan_data: Dict, profile: Dict) -> str:
    plan = plan_data["plan"]
    meta = plan_data["meta"]
    lang = meta.get("language", "ko")
    headers = TYPE_HEADER_KO if lang == "ko" else TYPE_HEADER_EN
    vlabels = VERDICT_LABEL_KO if lang == "ko" else VERDICT_LABEL_EN

    profile_keys = derive_profile_keys(profile)
    catalog = load_catalog()
    sources = catalog["_meta"]["sources"]

    out: List[str] = []

    if lang == "en":
        out.append("# Career Recommendation Result")
        out.append("")
        out.append("## User Profile")
    else:
        out.append("# 직업 추천 결과")
        out.append("")
        out.append("## 사용자 프로파일")
    out.append(f"- 나이/Age: {profile.get('age', '미상')}")
    out.append(f"- 학력/Education: {meta.get('education_normalized') or '미상'}")
    if profile.get("mbti"):
        out.append(f"- MBTI: {profile['mbti']}")
    if profile.get("enneagram"):
        out.append(f"- 에니어그램/Enneagram: Type {profile['enneagram']}")
    if profile.get("riasec"):
        out.append(f"- STRONG/RIASEC: {profile['riasec']}")
    if profile.get("multiple_intel"):
        out.append(f"- 다중지능/MI: {', '.join(profile['multiple_intel'])}")
    if profile.get("values"):
        out.append(f"- 가치/Values: {', '.join(profile['values'])}")
    if profile.get("interests"):
        out.append(f"- 관심/Interests: {', '.join(profile['interests'])}")
    if profile.get("current_job"):
        out.append(f"- 현재 직업/Current: {profile['current_job']}")
    out.append("")
    if lang == "en":
        out.append(
            "Recommendation generated by deterministic catalog matching pipeline "
            "(lib/pipeline.build_plan + lib/render.render_markdown). "
            "All job names are validated catalog entries; LLM free-form invention is structurally blocked."
        )
    else:
        out.append(
            "본 추천은 결정론적 카탈로그 매칭 파이프라인(lib/pipeline.build_plan + lib/render.render_markdown)이 "
            "생성합니다. 모든 직업명은 카탈로그(data/job_catalog.json)에 등록된 항목이며 LLM 자유 생성은 "
            "구조적으로 차단되어 있습니다. 26세·학사·ENFJ 9번처럼 *사용자별 맥락 코칭*은 본 추천 결과를 토대로 "
            "vision-clarity-coaching 등 후속 스킬에서 깊이 있게 다루어집니다."
        )
    out.append("")
    out.append("---")
    out.append("")

    for tkey in TYPE_KEYS:
        header = headers[tkey]
        emoji = TYPE_EMOJI[tkey]
        out.append(f"## {header} {emoji}")
        out.append("")
        slots = plan[tkey]["slots"]
        warning = plan[tkey].get("warning")
        if warning:
            out.append(f"> ⚠ {warning}")
            out.append("")
        for idx, job in enumerate(slots, 1):
            if job.get("_is_placeholder"):
                out.append(f"### {idx}. {job['ko']}")
                out.append(f"- **추천 이유**: {job['_verdict_reason']}")
                out.append(f"- **나이·학력 적합도**: {vlabels[job['_verdict']]}")
            else:
                title = f"{job['ko']} ({job['en']})" if lang == "ko" else f"{job['en']} ({job['ko']})"
                out.append(f"### {idx}. {title}")
                rationale = build_rationale_sentence(job, profile_keys, lang)
                out.append(f"- **추천 이유**: {rationale}")
                out.append(f"- **나이·학력 적합도**: {vlabels[job['_verdict']]} — {job['_verdict_reason']}")
                if job.get("note"):
                    out.append(f"- **자격·경로**: {job['note']}")
            out.append("")
        out.append("---")
        out.append("")

    # Work-type single section AFTER all 4 types
    if lang == "en":
        out.append("## Work Type Recommendation — Single Section After All 4 Types")
    else:
        out.append("## 직무 형태(Work Type) 추천 — 20개 직업 추천 완료 후 단일 섹션")
    out.append("")
    for tkey in TYPE_KEYS:
        header = headers[tkey]
        out.append(f"- **{header}**: {_work_type_advice(tkey, lang)}")
    out.append("")
    out.append("---")
    out.append("")

    if lang == "en":
        out.append("## Limitations & Caveats")
        out.append(
            "- This recommendation is a *simulation*; career decisions should also reference "
            "professional career counselors. The catalog reflects mainstream Korean labor-market evidence "
            "(KEIS Worknet, KOSIS KSCO, MOEL surveys, WEF Future of Jobs, McKinsey, OECD, KRIVET)."
        )
        out.append(
            "- Salary figures are intentionally omitted unless retrieved from the live web with attribution; "
            "consult the live Worknet (https://www.work.go.kr) for current wages."
        )
    else:
        out.append("## 한계·주의")
        out.append(
            "- 본 추천은 *시뮬레이션*이며 진로 결정은 본인 판단·전문 진로상담사 의견을 함께 참고하세요. "
            "카탈로그는 한국 노동시장 주류 근거(KEIS Worknet·KOSIS KSCO·고용노동부 실태조사·WEF·McKinsey·OECD·KRIVET)를 따릅니다."
        )
        out.append(
            "- 임금·연봉 수치는 출처 확보가 어려운 경우 의도적으로 *완전 생략*했습니다. 정확한 임금은 "
            "한국고용정보원 워크넷(https://www.work.go.kr) 및 고용노동부 고용형태별 근로실태조사에서 직접 확인하세요."
        )
    out.append(
        "- 나이·학력 외 *재정 상황·가족 책임·건강·지리* 등 추가 변수는 사용자 본인이 가장 잘 압니다."
    )
    out.append(
        "- 직업 시장은 빠르게 변하므로 추천 직업이 5년 후 동일하게 유효한지는 별도 점검이 필요합니다."
    )
    out.append("")
    out.append("### 카탈로그 출처 (학계·표준 자료 1:1 대조 가능)")
    for s in sources:
        out.append(f"- [{s['name']}]({s['url']}) — {s['scope']}")
    out.append("")
    out.append("---")
    out.append("")
    if lang == "en":
        out.append("## Next Steps")
        out.append("- Narrow down 1–3 candidates → use **vision-clarity-coaching** skill")
        out.append("- Turn vision into goal → use **vision-goal-reframing** skill")
        out.append("- Strategy & roadmap → use **vision-strategy-coach** skill")
        out.append("- Habit & follow-through → use **vision-follow-through-habits** skill")
        out.append("- Progress review → use **vision-progress-review** skill")
    else:
        out.append("## 다음 단계")
        out.append("- 20개 후보 중 1~3개 명료화 → **vision-clarity-coaching** 스킬")
        out.append("- 영감 → 현실 목표 변환 → **vision-goal-reframing** 스킬")
        out.append("- 전략·로드맵 → **vision-strategy-coach** 스킬")
        out.append("- 실행 지속력·습관 → **vision-follow-through-habits** 스킬")
        out.append("- 정기 점검 → **vision-progress-review** 스킬")
    return "\n".join(out)


def cli_main(argv):
    if len(argv) < 3:
        print("Usage: render.py profile.json plan.json [output.md]", file=__import__('sys').stderr)
        return 2
    with open(argv[1], "r", encoding="utf-8") as f:
        profile = json.load(f)
    with open(argv[2], "r", encoding="utf-8") as f:
        plan_data = json.load(f)
    md = render_markdown(plan_data, profile)
    if len(argv) >= 4:
        with open(argv[3], "w", encoding="utf-8") as f:
            f.write(md)
        return 0
    print(md)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(cli_main(sys.argv))
